'use client';

import { useMemo, useState } from 'react';

import { Badge } from '@/components/ui/badge';
import { Button, ButtonLink } from '@/components/ui/button';
import { Kicker } from '@/components/ui/card';
import { CheckIcon, HealthIcon, ScanIcon, TruckIcon } from '@/components/icons';
import {
  diagnose,
  SYMPTOMS,
  symptomSteps,
  type DiagnoseInput,
} from '@/lib/mechanic/engine';
import { researchSeam, type ResearchRef } from '@/lib/mechanic/search';
import type { AiInsight } from '@/lib/mechanic/ai';
import type { MechanicResult, Step, SymptomId, Triage } from '@/lib/mechanic/domain';
import { cn } from '@/lib/cn';

const TRIAGE: Record<Triage, { label: string; box: string; ring: string; chip: 'danger' | 'warning' | 'success' }> = {
  red: { label: 'Stop & fix now', box: 'border-danger-soft bg-danger-soft', ring: 'text-danger', chip: 'danger' },
  yellow: { label: 'Drive with care', box: 'border-warning-soft bg-warning-soft', ring: 'text-warning', chip: 'warning' },
  green: { label: 'Monitor / routine', box: 'border-success-soft bg-success-soft', ring: 'text-success', chip: 'success' },
};

export function Assistant({
  plan,
  allowance,
  remaining: initialRemaining,
}: {
  plan: string;
  allowance: number;
  remaining: number;
}) {
  const [symptom, setSymptom] = useState<SymptomId | null>(null);
  const [codes, setCodes] = useState('');
  const [description, setDescription] = useState('');
  const [ran, setRan] = useState(false);
  const [research, setResearch] = useState<ResearchRef[] | null>(null);
  const [remaining, setRemaining] = useState(initialRemaining);
  const isPro = plan === 'pro' || plan === 'fleet';
  const [deep, setDeep] = useState<{ insight: AiInsight; modeNote: string } | null>(null);
  const [deepState, setDeepState] = useState<'idle' | 'loading' | 'error'>('idle');
  const [deepError, setDeepError] = useState<string | null>(null);

  const input: DiagnoseInput = useMemo(
    () => ({
      codes: codes ? codes.split(/[,\n;]+/).map((s) => s.trim()).filter(Boolean) : [],
      symptom: symptom ?? undefined,
      description: description.trim() || undefined,
    }),
    [codes, symptom, description],
  );

  const result = useMemo(() => (ran ? diagnose(input) : null), [ran, input]);

  async function run() {
    const r = diagnose(input);
    setRan(true);
    setDeep(null);
    setDeepState('idle');
    setResearch(null);
    researchSeam.research(r).then(setResearch);
  }

  async function runDeep() {
    setDeepState('loading');
    setDeepError(null);
    try {
      const res = await fetch('/api/mechanic/deep', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(input),
      });
      const data = await res.json();
      if (!res.ok) {
        setDeepState('error');
        setDeepError(
          data.error === 'budget_exhausted'
            ? 'This month’s AI budget on Pro is used up. It resets on your billing date.'
            : data.error === 'plan_required'
              ? 'AI deep-dives need the Pro plan.'
              : 'Deep-dive is temporarily unavailable.',
        );
        return;
      }
      setRemaining(data.status.remaining);
      setDeep({
        insight: data.insight,
        modeNote:
          data.insight.mode === 'ai'
            ? 'Generated by AI'
            : 'Offline deep-dive (rule-based synthesis — no generative AI connected yet)',
      });
      setDeepState('idle');
    } catch {
      setDeepState('error');
      setDeepError('Network error running the deep-dive.');
    }
  }

  function useDemo() {
    setSymptom(null);
    setCodes('SPN 110');
    setDescription('Truck started running hot climbing the grade, fan is loud but temp is still climbing.');
    setRan(false);
  }

  function useTruckDemo() {
    // Simulates a code the driver would have synced from the app (web can't read OBD).
    setCodes('SPN 158');
    setSymptom(null);
    setDescription('Dash voltage reads 12.0 and dropps, lights are dim.');
  }

  return (
    <div>
      <div className="mb-8 max-w-2xl">
        <Badge tone="accent" className="mb-4 uppercase">Roadside Mechanic</Badge>
        <h1 className="text-4xl font-black tracking-tight text-ink md:text-5xl">
          Broke down? Let&rsquo;s sort it out.
        </h1>
        <p className="mt-4 text-lg text-muted">
          Describe what&rsquo;s wrong or drop in the fault codes from your truck. We decode the
          ECM signal, triage how safe it is to keep moving, and walk you through what you can fix
          at the roadside — and what needs a shop.
        </p>
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_1.15fr]">
        {/* Inputs */}
        <div className="rounded-2xl border border-line bg-white p-6 lg:sticky lg:top-24 lg:self-start">
          <div className="flex items-center justify-between">
            <Kicker>1 · What&rsquo;s happening?</Kicker>
            <div className="flex gap-2">
              <Button variant="ghost" size="sm" onClick={useDemo}>Demo: hot engine</Button>
              <Button variant="ghost" size="sm" onClick={useTruckDemo}>Demo: my truck</Button>
            </div>
          </div>

          <div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2">
            {SYMPTOMS.map((s) => (
              <button
                key={s.id}
                onClick={() => { setSymptom(s.id === symptom ? null : s.id); setRan(false); }}
                className={cn(
                  'rounded-xl border px-3.5 py-3 text-left transition',
                  symptom === s.id
                    ? 'border-accent bg-accent-soft'
                    : 'border-line bg-white hover:border-accent/40',
                )}
              >
                <div className="text-sm font-bold text-ink">{s.label}</div>
                <div className="text-xs text-faint">{s.hint}</div>
              </button>
            ))}
          </div>

          <label className="mt-5 block">
            <span className="mb-1.5 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-ink-2">
              <ScanIcon width={15} height={15} /> Fault codes (optional)
            </span>
            <textarea
              value={codes}
              onChange={(e) => { setCodes(e.target.value); setRan(false); }}
              placeholder="e.g. SPN 110, SPN 100 FMI 4"
              rows={2}
              className="w-full rounded-xl border border-line bg-bg-alt px-3.5 py-3 font-mono text-sm text-ink outline-none focus:border-accent"
            />
            <span className="mt-1 block text-xs text-faint">
              Find these in the Truck Buddy app under Vehicle health, or on the dash. Codes are optional — a symptom is enough.
            </span>
          </label>

          <label className="mt-4 block">
            <span className="mb-1.5 block text-xs font-bold uppercase tracking-wide text-ink-2">In your own words</span>
            <textarea
              value={description}
              onChange={(e) => { setDescription(e.target.value); setRan(false); }}
              placeholder="e.g. lost power going up a grade, black smoke from the stack…"
              rows={3}
              className="w-full rounded-xl border border-line bg-bg-alt px-3.5 py-3 text-sm text-ink outline-none focus:border-accent"
            />
          </label>

          <Button className="mt-5 w-full" size="lg" onClick={run}>
            <HealthIcon width={20} height={20} /> Diagnose it
          </Button>
          <p className="mt-3 text-center text-xs text-faint">
            Guidance is informational — see the note with your results.
          </p>
        </div>

        {/* Results */}
        <div className="space-y-5">
          {!result ? (
            <Placeholder />
          ) : (
            <>
              <Results
                result={result}
                research={research}
                steps={buildSteps(result, symptom)}
              />
              {isPro ? (
                <DeepDive
                  result={result}
                  onRun={runDeep}
                  state={deepState}
                  error={deepError}
                  insight={deep?.insight ?? null}
                  modeNote={deep?.modeNote ?? null}
                  remaining={remaining}
                  allowance={allowance}
                />
              ) : (
                <ProUpsell allowance={allowance} />
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function buildSteps(result: MechanicResult, symptom: SymptomId | null): Step[] {
  const extra = symptom ? symptomSteps(symptom) : [];
  const all = [
    ...result.steps,
    ...extra.map((s, i) => ({ ...s, order: result.steps.length + i + 1 })),
  ];
  const seen = new Set<string>();
  return all.filter((s) => {
    const key = s.title.toLowerCase();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

function Placeholder() {
  return (
    <div className="flex min-h-[360px] flex-col items-center justify-center rounded-2xl border border-dashed border-line bg-white p-10 text-center">
      <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-accent-soft text-accent">
        <TruckIcon width={30} height={30} />
      </div>
      <h2 className="mt-5 text-xl font-extrabold text-ink">No diagnosis yet</h2>
      <p className="mt-2 max-w-sm text-sm text-muted">
        Choose a symptom or enter a fault code, then hit <b>Diagnose it</b>. You&rsquo;ll get a
        safety triage and a step-by-step plan.
      </p>
    </div>
  );
}

function Results({
  result,
  research,
  steps,
}: {
  result: MechanicResult;
  research: ResearchRef[] | null;
  steps: Step[];
}) {
  const t = TRIAGE[result.triage];
  return (
    <>
      <div className={cn('rounded-2xl border-2 p-6', t.box)}>
        <div className="flex items-center gap-3">
          <span className={cn('text-2xl font-black', t.ring)}>{t.label.toUpperCase()}</span>
          <Badge tone={t.chip} dot>{result.triage === 'red' ? 'Do not drive' : result.triage === 'yellow' ? 'Service soon' : 'Monitor'}</Badge>
        </div>
        <h2 className="mt-2 text-2xl font-black text-ink">{result.headline}</h2>
        <p className="mt-2 text-sm text-ink-2">{result.summary}</p>
      </div>

      {result.stopConditions.length > 0 ? (
        <div className="rounded-2xl border border-danger-soft bg-danger-soft/60 p-5">
          <h3 className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-wide text-danger">
            Stop conditions
          </h3>
          <ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-ink-2">
            {result.stopConditions.map((s) => <li key={s}>{s}</li>)}
          </ul>
        </div>
      ) : null}

      {result.codes.length > 0 ? (
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-3 text-sm font-extrabold uppercase tracking-wide text-ink-2">Decoded fault codes</h3>
          <div className="space-y-3">
            {result.codes.map((c) => (
              <div key={c.raw} className="rounded-xl border border-line p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                    <span className="rounded-md bg-surface px-2 py-0.5 font-mono text-xs font-bold text-white">{c.raw}</span>
                    <span className="text-sm font-extrabold text-ink">{c.name}</span>
                    <span className="text-xs uppercase tracking-wide text-faint">{c.system}</span>
                  </div>
                  <Badge tone={c.severity === 'red' ? 'danger' : c.severity === 'yellow' ? 'warning' : 'success'} dot>{c.severity}</Badge>
                </div>
                <p className="mt-2 text-sm text-ink-2">{c.plain}</p>
                <p className="mt-1 text-xs text-danger">{c.keepDriving}</p>
              </div>
            ))}
          </div>
        </div>
      ) : null}

      {result.unknown.length > 0 ? (
        <div className="rounded-2xl border border-warning-soft bg-warning-soft/50 p-5">
          <h3 className="mb-2 text-sm font-extrabold uppercase tracking-wide text-warning">
            Codes we don&rsquo;t have offline
          </h3>
          <p className="text-sm text-ink-2">
            We don&rsquo;t recognize {result.unknown.join(', ')} in our roadside library, so we won&rsquo;t guess a
            fix. The steps below show how to handle it safely — record it exactly, do the safe
            baseline checks, and research it before driving.
          </p>
        </div>
      ) : null}

      {result.causes.length > 0 ? (
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-3 text-sm font-extrabold uppercase tracking-wide text-ink-2">Most likely causes</h3>
          <ul className="space-y-2.5">
            {result.causes.map((cause) => (
              <li key={cause.title} className="flex items-start justify-between gap-3 text-sm">
                <div>
                  <span className="font-bold text-ink">{cause.title}</span>
                  <p className="text-muted">{cause.detail}</p>
                </div>
                <span className="shrink-0 text-xs font-bold uppercase text-faint">{cause.likelihood}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {steps.length > 0 ? (
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-3 text-sm font-extrabold uppercase tracking-wide text-ink-2">Step-by-step</h3>
          <StepList steps={steps} />
        </div>
      ) : null}

      {research && research.length > 0 ? (
        <div className="rounded-2xl border border-line bg-white p-5">
          <h3 className="mb-3 flex items-center gap-2 text-sm font-extrabold uppercase tracking-wide text-ink-2">
            <SearchIcon width={15} height={15} /> Research this fault
          </h3>
          <div className="space-y-2">
            {research.map((r) => (
              <div key={r.text} className="flex items-center justify-between gap-3 rounded-xl bg-bg-alt px-3.5 py-2.5 text-sm">
                <span className={cn('text-ink-2', r.kind === 'note' && 'text-faint italic')}>
                  {r.kind === 'query' ? `"${r.text}"` : r.text}
                </span>
                {r.kind === 'query' ? <CopyButton text={r.text} /> : null}
              </div>
            ))}
          </div>
        </div>
      ) : null}

      <p className="px-2 text-xs leading-relaxed text-faint">{result.note}</p>
    </>
  );
}

function StepList({ steps, compact }: { steps: Step[]; compact?: boolean }) {
  return (
    <ol className="space-y-0">
      {steps.map((s) => (
        <li key={`${s.order}-${s.title}`} className={cn('flex gap-4 py-3', !compact && 'border-b border-line last:border-0')}>
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent-soft text-sm font-extrabold text-accent">
            {s.order}
          </div>
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2 text-[15px] font-bold text-ink">
              {s.title}
              {s.safety ? <Badge tone="danger" className="normal-case tracking-normal">safety</Badge> : null}
              {s.tool ? <span className="text-xs font-semibold text-faint">Needs: {s.tool}</span> : null}
              {s.time ? <span className="text-xs text-faint">~{s.time}</span> : null}
            </div>
            {s.detail ? <p className="mt-0.5 text-sm text-muted">{s.detail}</p> : null}
          </div>
        </li>
      ))}
    </ol>
  );
}

function DeepDive({
  result,
  onRun,
  state,
  error,
  insight,
  modeNote,
  remaining,
  allowance,
}: {
  result: MechanicResult;
  onRun: () => void;
  state: 'idle' | 'loading' | 'error';
  error: string | null;
  insight: AiInsight | null;
  modeNote: string | null;
  remaining: number;
  allowance: number;
}) {
  return (
    <div className="rounded-2xl border-2 border-accent bg-white p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <h3 className="flex items-center gap-2 text-sm font-extrabold uppercase tracking-wide text-ink">
          <span className="flex h-7 w-7 items-center justify-center rounded-md bg-accent text-xs font-black text-white">AI</span>
          Pro · Deep-dive insight
        </h3>
        <span className="rounded-full bg-bg-alt px-2.5 py-1 text-xs font-bold text-ink-2">
          {remaining} of {allowance} credits left this month
        </span>
      </div>

      <p className="mt-3 text-sm text-muted">
        Go deeper than the checklist — a synthesized read on root cause, what to carry, and when to
        call a shop. Uses 1 of your monthly credits.
      </p>

      {state === 'error' ? (
        <div className="mt-3 rounded-xl border border-danger-soft bg-danger-soft px-4 py-3 text-sm font-semibold text-danger">
          {error}
        </div>
      ) : null}

      {!insight ? (
        <Button className="mt-4 w-full" onClick={onRun} disabled={state === 'loading' || remaining <= 0} size="lg">
          {state === 'loading' ? 'Analyzing…' : remaining <= 0 ? 'Monthly budget used' : `Run deep-dive (1 credit) — ${result.triage.toUpperCase()} diagnosis`}
        </Button>
      ) : (
        <div className="mt-4 space-y-4">
          <div className="rounded-xl border border-success-soft bg-success-soft/50 px-4 py-3 text-[15px] font-bold text-success">
            {insight.verdict}
          </div>

          <div>
            <h4 className="text-xs font-extrabold uppercase tracking-wide text-ink-2">Root cause read</h4>
            <p className="mt-1 text-sm text-ink-2">{insight.rootCause}</p>
          </div>

          <ul className="space-y-2">
            {insight.points.map((p, i) => (
              <li key={i} className="flex gap-2.5 text-sm text-ink-2">
                <span className="mt-1 h-1.5 w-1.5 shrink-0 rounded-full bg-accent" />
                {p}
              </li>
            ))}
          </ul>

          <div>
            <h4 className="text-xs font-extrabold uppercase tracking-wide text-ink-2">Worth carrying</h4>
            <div className="mt-1.5 flex flex-wrap gap-2">
              {insight.carrySpares.map((s) => (
                <span key={s} className="rounded-lg bg-bg-alt px-2.5 py-1 text-xs font-semibold text-ink-2">{s}</span>
              ))}
            </div>
          </div>

          <p className="rounded-xl bg-bg-alt px-4 py-3 text-sm text-ink-2">
            <b className="font-bold text-danger">If you ignore it:</b> {insight.riskIfIgnored}
          </p>
          <p className="text-sm text-ink-2">
            <b className="font-bold text-ink">Call a shop when:</b> {insight.callShopWhen}
          </p>

          <div className="flex items-center justify-between gap-2 border-t border-line pt-3">
            <Badge tone={insight.confidence === 'high' ? 'success' : 'warning'}>
              Confidence · {insight.confidence}
            </Badge>
            {modeNote ? <span className="text-right text-[11px] italic text-faint">{modeNote}</span> : null}
          </div>
          <p className="text-[11px] leading-relaxed text-faint">{insight.disclaimer}</p>
        </div>
      )}
    </div>
  );
}

function ProUpsell({ allowance }: { allowance: number }) {
  return (
    <div className="rounded-2xl border border-dashed border-accent/50 bg-gradient-to-br from-accent-soft/60 to-white p-6">
      <div className="flex items-center gap-2">
        <span className="flex h-7 w-7 items-center justify-center rounded-md bg-accent text-xs font-black text-white">AI</span>
        <h3 className="text-sm font-extrabold uppercase tracking-wide text-ink">Deep-dive insight</h3>
        <span className="rounded-full bg-accent px-2.5 py-1 text-xs font-bold text-white">Pro</span>
      </div>
      <p className="mt-3 text-sm text-muted">
        A synthesized read on root cause, what to carry, and when to call a shop — beyond the basic
        checklist.
      </p>
      <ul className="mt-3 space-y-1.5 text-sm text-ink-2">
        <li className="flex items-center gap-2"><CheckMini /> {allowance} AI deep-dives included per month</li>
        <li className="flex items-center gap-2"><CheckMini /> Root-cause &amp; risk analysis</li>
        <li className="flex items-center gap-2"><CheckMini /> Parts &amp; spare guidance by system</li>
      </ul>
      <ButtonLink href="/#pricing" className="mt-4 w-full">Upgrade to Pro · $30/mo</ButtonLink>
    </div>
  );
}

function CheckMini() {
  return <CheckIcon width={16} height={16} className="text-accent" />;
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      className="shrink-0 rounded-lg bg-accent px-2.5 py-1.5 text-xs font-bold text-white transition hover:bg-accent-600"
      onClick={() => {
        navigator.clipboard?.writeText(text).catch(() => {});
        setCopied(true);
        setTimeout(() => setCopied(false), 1200);
      }}
    >
      {copied ? 'Copied' : 'Copy'}
    </button>
  );
}
// icons
function SearchIcon(p: { width: number; height: number }) {
  return (
    <svg width={p.width} height={p.height} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={1.8} strokeLinecap="round" strokeLinejoin="round" aria-hidden>
      <circle cx="11" cy="11" r="7" />
      <path d="M21 21l-4.3-4.3" />
    </svg>
  );
}
